{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let use_url_translation=ezini('URLTranslator','Translation')|eq('enabled')
     is_update=false()}
{section loop=$object.versions}
{section show=and($:item.status|eq(3),$:item.version|ne($object.current_version))}
{set is_update=true()}{/section}
{/section}
{section show=or($is_update, $object.class_identifier|ne('blog_post'))}
{set-block scope=root variable=subject}DONTSENDME{/set-block}
{set-block scope=root variable=from}{concat($object.current.creator.name|wash,' <', $sender, '>')}{/set-block}
{set-block scope=root variable=message_id}{concat('<node.',$object.main_node_id,'.eznotification','@',ezini("SiteSettings","SiteURL"),'>')}{/set-block}
{set-block scope=root variable=reply_to}{concat('<node.',$object.main_node_id,'.eznotification','@',ezini("SiteSettings","SiteURL"),'>')}{/set-block}
{set-block scope=root variable=references}{section name=Parent loop=$object.main_node.path_array}{concat('<node.',$:item,'.eznotification','@',ezini("SiteSettings","SiteURL"),'>')}{delimiter}{" "}{/delimiter}{/section}{/set-block}
{"This email is to inform you that an updated item has been published at %sitename."|i18n('design/standard/notification','',hash('%sitename',ezini("SiteSettings","SiteURL")))}
{"The item can be viewed by using the URL below."|i18n('design/standard/notification')}

{$object.name|wash}


{if is_set($object.data_map.body)}{$object.data_map.body.content.output.output_text|strip_tags|html_shorten(300)|trim}{/if}


{section-else}
{set-block scope=root variable=subject}{$object.content_class.name|wash} {'"%name" was published'|i18n('design/standard/notification', '', hash( '%name', $object.name|wash ))} [{ezini("SiteSettings","SiteURL")} - {$object.main_node.parent.name|wash}]{/set-block}
{set-block scope=root variable=from}{concat($object.owner.name,' <', $sender, '>')}{/set-block}
{set-block scope=root variable=message_id}{concat('<node.',$object.main_node_id,'.eznotification','@',ezini("SiteSettings","SiteURL"),'>')}{/set-block}
{set-block scope=root variable=reply_to}{concat('<node.',$object.main_node.parent_node_id,'.eznotification','@',ezini("SiteSettings","SiteURL"),'>')}{/set-block}
{set-block scope=root variable=references}{section name=Parent loop=$object.main_node.parent.path_array}{concat('<node.',$:item,'.eznotification','@',ezini("SiteSettings","SiteURL"),'>')}{delimiter}{" "}{/delimiter}{/section}{/set-block}

{$object.name|wash}


{if is_set($object.data_map.body)}{$object.data_map.body.content.output.output_text|strip_tags|html_shorten(300)|trim}{/if}


{/section}

Read more at: http://www.lifeisaspectrum.com

If you do not want to continue receiving these notifications, click here:

http://{ezini("SiteSettings","SiteURL")}{concat("publish/removefollower/mypwhash")|ezurl(no)}

-- 
{"%sitename notification system"
 |i18n('design/standard/notification',,
       hash('%sitename',ezini("SiteSettings","SiteURL")))}
{/let}
